# NumPy

NumPy is a Python package that allows the efficient handling on and operation on large arrays of numerical data. It's one of the most fundamental libraies for quantitative analysis.

In [2]:
import numpy as np

- NumPy Arrays  
- NumPy Indexing and Selection  
- NumPy Operations  
- NumPy Exercise (and Solution)

## Regular ndarray Object

In [3]:
# creating numpy array by casting a list
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
# creating a numpy array with the build in range function of python
a = np.array(range(24))

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
# creating a numpy array with the arange function of numpy
a1 = np.arange(0,5)
a1

array([0, 1, 2, 3, 4])

In [8]:
a2 = np.arange(1,11,2)
a2

array([1, 3, 5, 7, 9])

In [9]:
# creating arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# same for two-dimensional arrays
# passing tuple to array function (index 1 rows, index two columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# creating arrays of ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# returning evenly spaced numbers over a specified interval
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
# creating a matrix from a nested list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix = np.array(my_matrix)

In [14]:
np_matrix # two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(np_matrix)

numpy.ndarray

In [16]:
# numpy array as matrix
b = a.reshape((4, 6))

In [17]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
# creating an identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# numpy's random library
# used to model something like monte carlo simulation
np.random.rand(1) # retunrs random float between zero and one

array([0.57649515])

In [20]:
np.random.rand(5,4) # returns 5 x 4 matrix with random numbers berween zero and one
# uniform distribution, every number has the same odds of being picked

array([[0.65068102, 0.08116081, 0.17198829, 0.77728694],
       [0.59243363, 0.20498973, 0.22194342, 0.5552009 ],
       [0.0099158 , 0.28722005, 0.96778144, 0.12808799],
       [0.56301183, 0.10066685, 0.4909605 , 0.91774921],
       [0.75066562, 0.49978447, 0.56772121, 0.31315185]])

In [21]:
np.random.randn(5) # returns sample from the standard_normal distribution

array([-1.26374146,  1.02563194, -0.23662402, -0.43615547,  0.01832633])

In [22]:
np.random.randn(5,5)

array([[-6.00409174e-01, -6.14132816e-01, -6.37563335e-01,
        -2.41817055e-01,  3.05983228e-01],
       [-4.48366747e-01, -1.30298661e-03, -1.96869604e-01,
        -1.98832812e+00, -2.38425860e+00],
       [ 6.05103800e-01, -3.94469065e-01,  1.49981652e+00,
         1.30677417e-02, -7.98756184e-01],
       [ 4.57456610e-01, -2.00359644e+00,  7.14010594e-01,
        -5.14126294e-01, -9.29625452e-02],
       [ 5.72356929e-01, -1.42982843e+00,  4.54298020e-01,
        -1.19734462e+00,  1.12894354e+00]])

In [23]:
np.random.randint(1,100) # returns random integer from the "discrete uniform" distribution 

87

In [24]:
np.random.randint(1,100,10)

array([ 7, 49, 55, 75, 77, 90, 12, 41, 37, 14])

In [25]:
# array attributes and methods that are useful
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([43,  4, 26, 16,  8, 34, 32, 27, 12, 20])

In [27]:
# return an array with the same data but a different shape
arr.reshape(5,5) # reshape array to 5 by 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.shape # returns shape of one dimensional array

(25,)

In [29]:
arr.reshape(5,5).shape # shape of 5 by 5 matrix

(5, 5)

In [30]:
arr.dtype # data type of the array

dtype('int64')

In [31]:
ranarr.max() # max number in an array

43

In [32]:
ranarr.argmax() # index location of max number in an array

0

In [33]:
ranarr.min() # min number in an array

4

In [34]:
ranarr.argmin() # index location of min number in an array

1

## NumPy Operations

In [35]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# array addition on element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# array multiplication on element by element basis
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [39]:
# substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
# division
arr / arr # returns warning if 0 is in array
# 0/0 gets replaced with nan

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1567/3579412427.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # returns warning if 0 is in array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
1/arr # 1/0 gets replaced by infinity

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1567/255282349.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [43]:
# exponentials
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [44]:
# numpay comes along with array functions
np.sqrt(arr) # square root of every element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])