# NumPy

NumPy is a Python package that allows the efficient handling on and operation on large arrays of numerical data. It's one of the most fundamental libraies for quantitative analysis.

In [26]:
import numpy as np

- NumPy Arrays  
- NumPy Indexing and Selection  
- NumPy Operations  
- NumPy Exercise (and Solution)

## Regular ndarray Object

In [38]:
# creating numpy array by casting a list
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [41]:
type(np.array(my_list))

numpy.ndarray

In [48]:
# creating a numpy array with the build in range function of python
a = np.array(range(24))

In [40]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [50]:
# creating a numpy array with the arange function of numpy
a1 = np.arange(0,5)
a1

array([0, 1, 2, 3, 4])

In [54]:
a2 = np.arange(1,11,2)
a2

array([1, 3, 5, 7, 9])

In [56]:
# creating arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [58]:
# same for two-dimensional arrays
# passing tuple to array function (index 1 rows, index two columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
# creating arrays of ones
np.ones(4)

array([1., 1., 1., 1.])

In [67]:
# returning evenly spaced numbers over a specified interval
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [60]:
# creating a matrix from a nested list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix = np.array(my_matrix)

In [46]:
np_matrix # two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
type(np_matrix)

numpy.ndarray

In [34]:
# numpy array as matrix
b = a.reshape((4, 6))

In [30]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

<function ndarray.fill>