# NumPy

NumPy is a Python package that allows the efficient handling on and operation on large arrays of numerical data. It's one of the most fundamental libraies for quantitative analysis.

In [81]:
import numpy as np

- NumPy Arrays  
- NumPy Indexing and Selection  
- NumPy Operations  
- NumPy Exercise (and Solution)

## Regular ndarray Object

In [82]:
# creating numpy array by casting a list
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [83]:
type(np.array(my_list))

numpy.ndarray

In [84]:
# creating a numpy array with the build in range function of python
a = np.array(range(24))

In [85]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [86]:
# creating a numpy array with the arange function of numpy
a1 = np.arange(0,5)
a1

array([0, 1, 2, 3, 4])

In [87]:
a2 = np.arange(1,11,2)
a2

array([1, 3, 5, 7, 9])

In [88]:
# creating arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [89]:
# same for two-dimensional arrays
# passing tuple to array function (index 1 rows, index two columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [90]:
# creating arrays of ones
np.ones(4)

array([1., 1., 1., 1.])

In [91]:
# returning evenly spaced numbers over a specified interval
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [92]:
# creating a matrix from a nested list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix = np.array(my_matrix)

In [93]:
np_matrix # two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
type(np_matrix)

numpy.ndarray

In [95]:
# numpy array as matrix
b = a.reshape((4, 6))

In [96]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [97]:
# creating an identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
# numpy's random library
# used to model something like monte carlo simulation
np.random.rand(1) # retunrs random float between zero and one

array([0.45905242])

In [99]:
np.random.rand(5,4) # returns 5 x 4 matrix with random numbers berween zero and one
# uniform distribution, every number has the same odds of being picked

array([[0.01263643, 0.30444795, 0.29890627, 0.12404669],
       [0.88965279, 0.21394898, 0.56342396, 0.52291274],
       [0.2601142 , 0.06447162, 0.02609444, 0.57530667],
       [0.88942663, 0.86947132, 0.52439381, 0.90419931],
       [0.91282067, 0.32611073, 0.87523813, 0.68231301]])

In [100]:
np.random.randn(5) # returns sample from the standard_normal distribution

array([ 1.14891994, -0.65188852,  0.99242425,  0.4744555 , -0.52474957])

In [101]:
np.random.randn(5,5)

array([[-1.48319055, -1.56009613, -1.1284373 , -1.58224843, -0.37278075],
       [ 1.10551627, -0.60386486,  0.16556862,  0.00375611, -0.48985051],
       [ 0.2767523 ,  0.08571933,  0.26668175,  0.00886853, -1.26684168],
       [-2.07015183, -0.48987314, -1.38059874,  0.31931873,  0.20869716],
       [ 1.04736652,  0.62102403, -0.18333182, -0.92647567, -1.00194219]])

In [102]:
np.random.randint(1,100) # returns random integer from the "discrete uniform" distribution 

72

In [103]:
np.random.randint(1,100,10)

array([ 8,  7,  1, 94, 50, 98, 71, 55, 56, 49])

In [104]:
# array attributes and methods that are useful
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [105]:
ranarr = np.random.randint(0,50,10)
ranarr

array([33, 30,  6,  4, 48, 45, 27, 12, 41, 25])

In [106]:
# return an array with the same data but a different shape
arr.reshape(5,5) # reshape array to 5 by 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [107]:
arr.shape # returns shape of one dimensional array

(25,)

In [108]:
arr.reshape(5,5).shape # shape of 5 by 5 matrix

(5, 5)

In [109]:
arr.dtype # data type of the array

dtype('int64')

In [110]:
ranarr.max() # max number in an array

48

In [111]:
ranarr.argmax() # index location of max number in an array

4

In [112]:
ranarr.min() # min number in an array

4

In [113]:
ranarr.argmin() # index location of min number in an array

3

## NumPy Operations

In [114]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
# array addition on element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [116]:
# array multiplication on element by element basis
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [117]:
# substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [118]:
# division
arr / arr # returns warning if 0 is in array
# 0/0 gets replaced with nan

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/897384303.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # returns warning if 0 is in array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [119]:
1/arr # 1/0 gets replaced by infinity

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/659140530.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr # 1/0 gets replaced by infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [120]:
# exponentials
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [121]:
# numpy comes along with array functions
np.sqrt(arr) # square root of every element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [122]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [123]:
# what's the maximum value in an array
np.max(arr)

9

In [124]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [125]:
np.log(arr)

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## NumPy for Indexing and Selection

In [126]:
arr = np.arange(0,11)

In [127]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
# bracket indexing and selection
# element at index 8
arr[8]

8

In [129]:
# slice notation
arr[1:5]

array([1, 2, 3, 4])

In [130]:
# everything up to a certain position but not including it
arr[:5]

array([0, 1, 2, 3, 4])

In [131]:
# everything from a certain position up to the end
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [132]:
# broadcasting a reasignment
# grab a slice and set it equal to a certain value
arr[0:5] = 100

In [133]:
arr # five elements now have the number 100, this is known as broadcasting

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [134]:
# resetting the array
arr = np.arange(0,11)

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
# example: slice of array is a pointer to the original array
# changing the slice changes the original array as well
# the data is not actually copied (avoids memory problems)
slice_of_arr = arr[0:6]

In [137]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [138]:
slice_of_arr[:] = 99

In [139]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [140]:
arr # notice that slice was just a pointer

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [141]:
# if you want to have a copy you've to explicitly say so
arr_copy = arr.copy()

In [142]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [143]:
arr_copy[:] = 200

In [144]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [145]:
arr # change doesn't affect original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [146]:
# indexing twodimensional array (matrix)
# matr[row, col]
# or matr[row][col]
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [147]:
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [148]:
# indexing entire row
mat[0] # returns first row

array([ 5, 10, 15])

In [149]:
# grab individual element
# matr[row, col]
mat[1,1] # second row, second element

25

In [150]:
# or matr[row][col]
mat[2][2] # third row, third element

45

In [153]:
# slicing a matrix
mat[:2,] # grabbing row two and three

array([[ 5, 10, 15],
       [20, 25, 30]])

In [158]:
mat[:2,1:] # grabbing row two and three, column two and three

array([[10, 15],
       [25, 30]])

In [165]:
mat[1:3,0:2] # grabbing another square

array([[20, 25],
       [35, 40]])

In [166]:
# or
mat[1:,:2] # grabbing another square

array([[20, 25],
       [35, 40]])