# NumPy

NumPy is a Python package that allows the efficient handling on and operation on large arrays of numerical data. It's one of the most fundamental libraies for quantitative analysis.

In [2]:
import numpy as np

- NumPy Arrays  
- NumPy Indexing and Selection  
- NumPy Operations  
- NumPy Exercise (and Solution)

## Regular ndarray Object

In [3]:
# creating numpy array by casting a list
my_list = [1, 2, 3]
np.array(my_list)

array([1, 2, 3])

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
# creating a numpy array with the build in range function of python
a = np.array(range(24))

In [6]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [7]:
# creating a numpy array with the arange function of numpy
a1 = np.arange(0,5)
a1

array([0, 1, 2, 3, 4])

In [8]:
a2 = np.arange(1,11,2)
a2

array([1, 3, 5, 7, 9])

In [9]:
# creating arrays of zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
# same for two-dimensional arrays
# passing tuple to array function (index 1 rows, index two columns)
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
# creating arrays of ones
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# returning evenly spaced numbers over a specified interval
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [13]:
# creating a matrix from a nested list
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np_matrix = np.array(my_matrix)

In [14]:
np_matrix # two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
type(np_matrix)

numpy.ndarray

In [16]:
# numpy array as matrix
b = a.reshape((4, 6))

In [17]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [18]:
# creating an identiy matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
# numpy's random library
# used to model something like monte carlo simulation
np.random.rand(1) # retunrs random float between zero and one

array([0.37521105])

In [20]:
np.random.rand(5,4) # returns 5 x 4 matrix with random numbers berween zero and one
# uniform distribution, every number has the same odds of being picked

array([[0.03102351, 0.48402309, 0.7422533 , 0.89725759],
       [0.57702293, 0.34289534, 0.30137174, 0.05121673],
       [0.57041396, 0.85197686, 0.87929654, 0.64120171],
       [0.64120012, 0.9151607 , 0.54278444, 0.62121684],
       [0.33638859, 0.42004566, 0.73272773, 0.22517464]])

In [21]:
np.random.randn(5) # returns sample from the standard_normal distribution

array([-1.59917961, -2.03398327,  0.53646987, -1.06502547,  0.25181364])

In [22]:
np.random.randn(5,5)

array([[-1.5565497 ,  1.69872624, -0.25774533, -0.87589856,  0.03982096],
       [-1.25031459, -3.2884616 , -0.18160758,  0.37055099,  0.06055805],
       [-0.65620254, -0.50109099,  0.21406414, -0.50271548,  1.47608128],
       [-0.54479116, -0.68557177, -0.63302297, -0.23349742, -0.4322695 ],
       [-0.51229778, -0.79450861, -0.65543728, -2.07253882, -1.98422148]])

In [23]:
np.random.randint(1,100) # returns random integer from the "discrete uniform" distribution 

94

In [24]:
np.random.randint(1,100,10)

array([68, 95, 71, 25, 69, 16, 60, 39, 32, 32])

In [25]:
# array attributes and methods that are useful
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)
ranarr

array([ 8, 20, 12, 36, 29, 38, 42,  7,  8, 17])

In [27]:
# return an array with the same data but a different shape
arr.reshape(5,5) # reshape array to 5 by 5 matrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [28]:
arr.shape # returns shape of one dimensional array

(25,)

In [29]:
arr.reshape(5,5).shape # shape of 5 by 5 matrix

(5, 5)

In [30]:
arr.dtype # data type of the array

dtype('int64')

In [31]:
ranarr.max() # max number in an array

42

In [32]:
ranarr.argmax() # index location of max number in an array

6

In [33]:
ranarr.min() # min number in an array

7

In [34]:
ranarr.argmin() # index location of min number in an array

7

## NumPy Operations

In [35]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
# array addition on element by element basis
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
# array multiplication on element by element basis
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [38]:
# substraction
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
# division
arr / arr # returns warning if 0 is in array
# 0/0 gets replaced with nan

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/897384303.py:2: RuntimeWarning: invalid value encountered in true_divide
  arr / arr # returns warning if 0 is in array


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [40]:
1/arr # 1/0 gets replaced by infinity

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/659140530.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr # 1/0 gets replaced by infinity


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [41]:
# exponentials
arr ** 3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [42]:
# numpy comes along with array functions
np.sqrt(arr) # square root of every element

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [43]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [44]:
# what's the maximum value in an array
np.max(arr)

9

In [45]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [46]:
np.log(arr)

/var/folders/7c/6tn50bjd30l3zb0p8_7mr94m0000gn/T/ipykernel_1558/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

## NumPy for Indexing and Selection

In [47]:
arr = np.arange(0,11)

In [48]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# bracket indexing and selection
# element at index 8
arr[8]

8

In [50]:
# slice notation
arr[1:5]

array([1, 2, 3, 4])

In [51]:
# everything up to a certain position but not including it
arr[:5]

array([0, 1, 2, 3, 4])

In [52]:
# everything from a certain position up to the end
arr[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
# broadcasting a reasignment
# grab a slice and set it equal to a certain value
arr[0:5] = 100

In [54]:
arr # five elements now have the number 100, this is known as broadcasting

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
# resetting the array
arr = np.arange(0,11)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
# example: slice of array is a pointer to the original array
# changing the slice changes the original array as well
# the data is not actually copied (avoids memory problems)
slice_of_arr = arr[0:6]

In [60]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [62]:
slice_of_arr[:] = 99

In [64]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr # notice that slice was just a pointer

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [69]:
# if you want to have a copy you've to explicitly say so
arr_copy = arr.copy()

In [70]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [71]:
arr_copy[:] = 200

In [72]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [74]:
arr # change doesn't affect original array

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])